// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "Link":return img`
........................
.....ffff...............
...fff99fff.............
..fff9999fff............
.fff666666fff...........
.ff699999966f...........
.f69ffffff96f...........
.ffff6666ffff...........
ff6fbf88fbf6ff..........
f6681fddf1866f..........
.ffffddddd66f...........
fddddf88866f............
fbbbbf9999f86...........
fbbbbf9999fd8...........
.fccf85588f88...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image1":
            case "Little Mac":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f f f f f . . . . . 
. . . . f d d d d d d . . . . . 
. . . . f d d d d f d . . . . . 
. . . . f d d d d f d d . . . . 
. . . . f d d d d d d d . . . . 
. . . . . f f 1 1 1 f f . . . . 
. . 7 7 f f f f f f f f f 7 7 . 
. . 7 7 7 f f f f f f f 7 7 7 . 
. . 7 7 f f f f f f f f f 7 7 . 
. . . . d d d . . . d d d . . . 
. . . . 7 f f . . . 7 f f . . . 
. . . . 7 f f f . . 7 f f f . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage":return img`
........222.........
......2222222.......
.....212222222......
....2122272271......
....22222272771.....
....22222722777.....
.....2fffff2277.....
.....f.....f222.....
...........f2ff.....
............f.......
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
